<?php
	error_reporting(0);
	header("Content-Type: text/html; charset=utf-8");

	$article_id = $_GET['article'];
	$article_url = 'https://www.ncbi.nlm.nih.gov/pubmed/'.$article_id.'?report=xml&format=text';
	
	
	$fileContents = file_get_contents($article_url);
	$fileContents = mb_convert_encoding($fileContents, 'HTML-ENTITIES', "UTF-8");
	$fileContents = htmlspecialchars_decode($fileContents);
	$fileContents = str_replace('&','qqqqppppbbbbdddd',$fileContents);
	$xml = simplexml_load_string($fileContents);
	$json = json_encode($xml);
	$json = str_replace('qqqqppppbbbbdddd','&',$json);
	$array = json_decode($json,TRUE);
//	print_r($array);die();
	$PubmedArticle_MedlineCitation_PMID                                              = (is_array($array['PubmedArticle']['MedlineCitation']['PMID']                                                             ))?$array['PubmedArticle']['MedlineCitation']['PMID']                                                                        [0]:$array['PubmedArticle']['MedlineCitation']['PMID']                                                                     ;
	$PubmedArticle_MedlineCitation_Article_Journal_Title                             = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['Journal']['Title']                                      ))?$array['PubmedArticle']['MedlineCitation']['Article']['Journal']['Title']                                                 [0]:$array['PubmedArticle']['MedlineCitation']['Article']['Journal']['Title']                                              ;
	$PubmedArticle_MedlineCitation_Article_Journal_ISOAbbreviation                   = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['Journal']['ISOAbbreviation']                            ))?$array['PubmedArticle']['MedlineCitation']['Article']['Journal']['ISOAbbreviation']                                       [0]:$array['PubmedArticle']['MedlineCitation']['Article']['Journal']['ISOAbbreviation']                                    ;
	$PubmedArticle_MedlineCitation_Article_ArticleTitle                              = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['ArticleTitle']                                          ))?$array['PubmedArticle']['MedlineCitation']['Article']['ArticleTitle']                                                     [0]:$array['PubmedArticle']['MedlineCitation']['Article']['ArticleTitle']                                                  ;
	$PubmedArticle_MedlineCitation_Article_Pagination_MedlinePgn                     = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['Pagination']['MedlinePgn']                              ))?$array['PubmedArticle']['MedlineCitation']['Article']['Pagination']['MedlinePgn']                                         [0]:$array['PubmedArticle']['MedlineCitation']['Article']['Pagination']['MedlinePgn']                                      ;
	$PubmedArticle_MedlineCitation_Article_ELocationID                               = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['ELocationID']                                           ))?$array['PubmedArticle']['MedlineCitation']['Article']['ELocationID']                                                      [0]:$array['PubmedArticle']['MedlineCitation']['Article']['ELocationID']                                                   ;
	$PubmedArticle_MedlineCitation_Article_Abstract_AbstractText                     = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['Abstract']['AbstractText']                              ))?$array['PubmedArticle']['MedlineCitation']['Article']['Abstract']['AbstractText']                                         [0]:$array['PubmedArticle']['MedlineCitation']['Article']['Abstract']['AbstractText']                                      ;
	$PubmedArticle_MedlineCitation_Article_Language                                  = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['Language']                                              ))?$array['PubmedArticle']['MedlineCitation']['Article']['Language']                                                         [0]:$array['PubmedArticle']['MedlineCitation']['Article']['Language']                                                      ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_GrantID                   = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['GrantID']                    		))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['GrantID']                               	 [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['GrantID']                            		;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Acronym                   = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Acronym']                    		))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Acronym']                               	 [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Acronym']                            		;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Agency                    = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Agency']                     		))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Agency']                                	 [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Agency']                             		;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Country                   = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Country']                    		))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Country']                               	 [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['Country']                            		;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_GrantID                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['GrantID']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['GrantID']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['GrantID']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Acronym                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Acronym']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Acronym']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Acronym']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Agency                  = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Agency']                     ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Agency']                                [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Agency']                             ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Country                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Country']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Country']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['0']['Country']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_GrantID                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['GrantID']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['GrantID']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['GrantID']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Acronym                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Acronym']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Acronym']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Acronym']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Agency                  = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Agency']                     ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Agency']                                [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Agency']                             ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Country                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Country']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Country']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['1']['Country']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_GrantID                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['GrantID']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['GrantID']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['GrantID']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Acronym                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Acronym']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Acronym']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Acronym']                            ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Agency                  = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Agency']                     ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Agency']                                [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Agency']                             ;
	$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Country                 = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Country']                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Country']                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['GrantList']['Grant']['2']['Country']                            ;
	$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_0     = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']	            ))?$array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']['0']                         :$array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']	                    ;
	$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_1     = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']	            ))?$array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']['1']                         :''																									                    ;
	$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_2     = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']	            ))?$array['PubmedArticle']['MedlineCitation']['Article']['PublicationTypeList']['PublicationType']['2']                         :''																									                    ;
	$PubmedArticle_MedlineCitation_Article_ArticleDate_Year                          = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Year']                                   ))?$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Year']                                              [0]:$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Year']                                           ;
	$PubmedArticle_MedlineCitation_Article_ArticleDate_Month                         = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Month']                                  ))?$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Month']                                             [0]:$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Month']                                          ;
	$PubmedArticle_MedlineCitation_Article_ArticleDate_Day                           = (is_array($array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Day']                                    ))?$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Day']                                               [0]:$array['PubmedArticle']['MedlineCitation']['Article']['ArticleDate']['Day']                                            ;
	$PubmedArticle_MedlineCitation_MedlineJournalInfo_Country                        = (is_array($array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['Country']                                    ))?$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['Country']                                               [0]:$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['Country']                                            ;
	$PubmedArticle_MedlineCitation_MedlineJournalInfo_MedlineTA                      = (is_array($array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['MedlineTA']                                  ))?$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['MedlineTA']                                             [0]:$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['MedlineTA']                                          ;
	$PubmedArticle_MedlineCitation_MedlineJournalInfo_NlmUniqueID                    = (is_array($array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['NlmUniqueID']                                ))?$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['NlmUniqueID']                                           [0]:$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['NlmUniqueID']                                        ;
	$PubmedArticle_MedlineCitation_MedlineJournalInfo_ISSNLinking                    = (is_array($array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['ISSNLinking']                                ))?$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['ISSNLinking']                                           [0]:$array['PubmedArticle']['MedlineCitation']['MedlineJournalInfo']['ISSNLinking']                                        ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_0_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_0_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['0']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_1_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_1_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['1']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_2_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_2_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['2']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_3_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_3_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['3']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_4_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_4_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['4']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_5_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_5_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['5']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_6_RegistryNumber            = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['RegistryNumber']                  ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['RegistryNumber']                             [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['RegistryNumber']                          ;
	$PubmedArticle_MedlineCitation_ChemicalList_Chemical_6_NameOfSubstance           = (is_array($array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['NameOfSubstance']                 ))?$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['NameOfSubstance']                            [0]:$array['PubmedArticle']['MedlineCitation']['ChemicalList']['Chemical']['6']['NameOfSubstance']                         ;
	$PubmedArticle_MedlineCitation_CitationSubset                                    = (is_array($array['PubmedArticle']['MedlineCitation']['CitationSubset']                                                   ))?$array['PubmedArticle']['MedlineCitation']['CitationSubset']                                                              [0]:$array['PubmedArticle']['MedlineCitation']['CitationSubset']                                                           ;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['DescriptorName']            ))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['DescriptorName']                       [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['DescriptorName']                    ;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['QualifierName']	           			;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['0']['QualifierName']                   	 [1]:''																								                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['QualifierName']	                	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['1']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['QualifierName']	                	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['2']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['3']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['4']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['5']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['6']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['7']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['8']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_DescriptorName      = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['DescriptorName']      		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['DescriptorName']                  	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['DescriptorName']               		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_QualifierName_0     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['QualifierName']                   	 [0]:$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['QualifierName']                		;
	$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_QualifierName_1     = (is_array($array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['QualifierName']       		))?$array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading']['9']['QualifierName']                   	 [1]:''																								                   		;
	$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Year          = (is_array($array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Year']                      				))?$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Year']                               				 [0]:$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Year']                              				;
	$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Month         = (is_array($array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Month']                     				))?$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Month']                              				 [0]:$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Month']                             				;
	$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Day           = (is_array($array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Day']                       				))?$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Day']                                				 [0]:$array['PubmedArticle']['PubmedData']['History']['PubMedPubDate'][0]['Day']                               				;
	$PubmedArticle_PubmedData_PublicationStatus                                      = (is_array($array['PubmedArticle']['PubmedData']['PublicationStatus']                                                     ))?$array['PubmedArticle']['PubmedData']['PublicationStatus']                                                                [0]:$array['PubmedArticle']['PubmedData']['PublicationStatus']                                                             ;

//	$fileContents= mb_convert_encoding(file_get_contents($article_url), 'HTML-ENTITIES', "UTF-8");
//	$fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
//	$fileContents = trim(str_replace('"', "'", $fileContents));
//	$simpleXml = simplexml_load_string($fileContents);
//	$json = json_encode($simpleXml);



//	print_r($json);die();
//	
//	$title 			= $array['PubmedArticle']['MedlineCitation']['Article']['ArticleTitle'];
//	$abstract 		= $array['PubmedArticle']['MedlineCitation']['Article']['Abstract']['AbstractText'];
//	$mesh_headings 	= $array['PubmedArticle']['MedlineCitation']['MeshHeadingList']['MeshHeading'];
//	
	$output .= '<tr>';
	$output .= '
		<td>'.$PubmedArticle_MedlineCitation_PMID                                                       .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_Journal_Title                                      .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_Journal_ISOAbbreviation                            .'</td>
		<td style="font-size: 1px;">'.$PubmedArticle_MedlineCitation_Article_ArticleTitle                                       .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_Pagination_MedlinePgn                              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_ELocationID                                        .'</td>
		<td style="font-size: 1px;">'.$PubmedArticle_MedlineCitation_Article_Abstract_AbstractText                              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_Language                                           .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_GrantID                            .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Acronym                            .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Agency                             .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_Country                            .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_GrantID                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Acronym                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Agency                           .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_0_Country                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_GrantID                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Acronym                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Agency                           .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_1_Country                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_GrantID                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Acronym                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Agency                           .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_GrantList_Grant_2_Country                          .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_PublicationTypeList_PublicationType_2              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_ArticleDate_Year                                   .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_ArticleDate_Month                                  .'</td>
		<td>'.$PubmedArticle_MedlineCitation_Article_ArticleDate_Day                                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MedlineJournalInfo_Country                                 .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MedlineJournalInfo_MedlineTA                               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MedlineJournalInfo_NlmUniqueID                             .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MedlineJournalInfo_ISSNLinking                             .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_0_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_0_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_1_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_1_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_2_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_2_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_3_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_3_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_4_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_4_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_5_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_5_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_6_RegistryNumber                     .'</td>
		<td>'.$PubmedArticle_MedlineCitation_ChemicalList_Chemical_6_NameOfSubstance                    .'</td>
		<td>'.$PubmedArticle_MedlineCitation_CitationSubset                                             .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_0_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_1_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_2_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_3_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_4_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_5_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_6_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_7_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_8_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_DescriptorName               .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_QualifierName_0              .'</td>
		<td>'.$PubmedArticle_MedlineCitation_MeshHeadingList_MeshHeading_9_QualifierName_1              .'</td>
		<td>'.$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Year                   .'</td>
		<td>'.$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Month                  .'</td>
		<td>'.$PubmedArticle_PubmedData_History_PubMedPubDate_PubStatus_received_Day                    .'</td>
		<td>'.$PubmedArticle_PubmedData_PublicationStatus                                               .'</td>
	';
//	foreach($mesh_headings as $mesh_heading) {
//		$output .= '
//			<td>'.$mesh_heading['DescriptorName'].'</td>
//		';
//	}
	$output .= '</tr>';
	
//	$output .= '"'.$_GET['article'].'":'.$json.',';
//	$output .= $json;
	echo $output;







